### ISSUE TITLE
你们老师真的会用这个吗.....

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/random-student#1]
不太实用)可以加一个excel导入的功能

**Comment by lingbopro** [comment]
我们老师真的会用。
~~不过第一次用是随机抽取要惩罚的人（~~

**Comment by Minemetero** [comment]
function deleteAll() {
    if(window.confirm('确认要全部删除吗？\n所有数据将会永远丢失（真的很久！）')) {
        students = [];
    }
    refreshStudents();
}
MC好评

**Comment by lingbopro** [comment]
> 不太实用)可以加一个excel导入的功能

彳亍，回头我研究一下

**Comment by Minemetero** [comment]
> 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~

你们老师是把学号放进去吗

**Comment by lingbopro** [comment]
> 不太实用)可以加一个excel导入的功能

而且Excel复制一列单元格纯文本粘贴出来就是一行一个  
所以我在添加那才会用一行一个

**Comment by lingbopro** [comment]
> function deleteAll() {
>     if(window.confirm('确认要全部删除吗？\n所有数据将会永远丢失（真的很久！）')) {
>         students = [];
>     }
>     refreshStudents();
> }
> MC好评

doge

**Comment by Minemetero** [comment]
GitHub-Easy-Hosts 已经10年没开张了

**Comment by lingbopro** [comment]
> > 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~
> 
> 你们老师是把学号放进去吗

是名字  
不过主要由我操作

**Comment by Minemetero** [comment]
> > > 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~
> > 
> > 
> > 你们老师是把学号放进去吗
> 
> 是名字 不过主要由我操作

电教委员a?

**Comment by lingbopro** [comment]
> GitHub-Easy-Hosts 已经10年没开张了

这个嘛  
总得休息一会的  
（而且你把easy和github拼反了

**Comment by lingbopro** [comment]
> > > > 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~
> > > 
> > > 
> > > 你们老师是把学号放进去吗
> > 
> > 是名字 不过主要由我操作
> 
> 电教委员a?

算是吧  
我们班叫信息课代表

**Comment by Minemetero** [comment]
> > GitHub-Easy-Hosts 已经10年没开张了
> 
> 这个嘛 总得休息一会的 （而且你把easy和github拼反了

休息啥啊,写代码就是休息(给我爬起来干活)

**Comment by lingbopro** [comment]
> > GitHub-Easy-Hosts 已经10年没开张了
> 
> 这个嘛  
> 总得休息一会的  
> （而且你把easy和github拼反了  

不过我的提交热力图雀食有些少啊  

![IMG_20240520_192316.jpg](https://github.com/lingbopro/random-student/assets/148617407/ae28db1e-9167-401f-879e-fb617f13bf9a)

**Comment by Minemetero** [comment]
> > > > > 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~
> > > > 
> > > > 
> > > > 你们老师是把学号放进去吗
> > > 
> > > 
> > > 是名字 不过主要由我操作
> > 
> > 
> > 电教委员a?
> 
> 算是吧 我们班叫信息课代表

你在哪里(城市)生活?

**Comment by lingbopro** [comment]
> > > GitHub-Easy-Hosts 已经10年没开张了
> > 
> > 这个嘛 总得休息一会的 （而且你把easy和github拼反了
> 
> 休息啥啊,写代码就是休息(给我爬起来干活)

我真就

**Comment by lingbopro** [comment]
> > > > > > 我们老师真的会用。 ~不过第一次用是随机抽取要惩罚的人（~
> > > > > 
> > > > > 
> > > > > 你们老师是把学号放进去吗
> > > > 
> > > > 
> > > > 是名字 不过主要由我操作
> > > 
> > > 
> > > 电教委员a?
> > 
> > 算是吧 我们班叫信息课代表
> 
> 你在哪里(城市)生活?

北京（喜

**Comment by Minemetero** [comment]
> > > GitHub-Easy-Hosts 已经10年没开张了
> > 
> > 
> > 这个嘛
> > 总得休息一会的
> > （而且你把easy和github拼反了
> 
> 不过我的提交热力图雀食有些少啊
> 
> ![IMG_20240520_192316.jpg](https://private-user-images.githubusercontent.com/148617407/332049025-ae28db1e-9167-401f-879e-fb617f13bf9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDQ1MTEsIm5iZiI6MTcxNjIwNDIxMSwicGF0aCI6Ii8xNDg2MTc0MDcvMzMyMDQ5MDI1LWFlMjhkYjFlLTkxNjctNDAxZi04NzllLWZiNjE3ZjEzYmY5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMTIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzFiZmU2YjY5ZjYzZjMzZjQ5ZWM3ZjViZWY3MGI2NzA5ZTcyOWU3MzBjMzY4ZTVmZmMwZjE1OGExNTdhOWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TLdbNEGAS9iInkGf1M_cLkAO0vaXbDapFoOk8A9nL_E)

感动哭了

**Comment by lingbopro** [comment]
> > > > GitHub-Easy-Hosts 已经10年没开张了
> > > 
> > > 
> > > 这个嘛
> > > 总得休息一会的
> > > （而且你把easy和github拼反了
> > 
> > 不过我的提交热力图雀食有些少啊
> > 
> > ![IMG_20240520_192316.jpg](https://private-user-images.githubusercontent.com/148617407/332049025-ae28db1e-9167-401f-879e-fb617f13bf9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDQ1MTEsIm5iZiI6MTcxNjIwNDIxMSwicGF0aCI6Ii8xNDg2MTc0MDcvMzMyMDQ5MDI1LWFlMjhkYjFlLTkxNjctNDAxZi04NzllLWZiNjE3ZjEzYmY5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMTIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzFiZmU2YjY5ZjYzZjMzZjQ5ZWM3ZjViZWY3MGI2NzA5ZTcyOWU3MzBjMzY4ZTVmZmMwZjE1OGExNTdhOWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TLdbNEGAS9iInkGf1M_cLkAO0vaXbDapFoOk8A9nL_E)
> 
> 感动哭了

啊

**Comment by Minemetero** [comment]
你想不想知道我在哪里:)

**Comment by lingbopro** [comment]
> 你想不想知道我在哪里:)

~~肯定想啊~~

**Comment by Minemetero** [comment]
全班就你一个会敲代码吗?

**Comment by Minemetero** [comment]
> > 你想不想知道我在哪里:)
> 
> ~肯定想啊~

不你不想

**Comment by lingbopro** [comment]
> 全班就你一个会敲代码吗?

也不是  
还有一个，是我的good friend  
不过他没GitHub的号  
我早就劝他注册一个了  
结果一拖再拖

**Comment by Minemetero** [comment]
35.677, 139.775

**Comment by Minemetero** [comment]
> > 全班就你一个会敲代码吗?
> 
> 也不是 还有一个，是我的good friend 不过他没GitHub的号 我早就劝他注册一个了 结果一拖再拖

你帮他搞一个我想见见

**Comment by lingbopro** [comment]
> > > 全班就你一个会敲代码吗?
> > 
> > 也不是 还有一个，是我的good friend 不过他没GitHub的号 我早就劝他注册一个了 结果一拖再拖
> 
> 你帮他搞一个我想见见

明天我去学校~~武力逼迫~~跟他友好交流一下

**Comment by lingbopro** [comment]
> 35.677, 139.775

啊？  

![Screenshot_20240520_204841_com.microsoft.emmx.jpg](https://github.com/lingbopro/random-student/assets/148617407/1bc5367f-0b27-46c2-b990-8693c80c9a88)

**Comment by lingbopro** [comment]
> > > 全班就你一个会敲代码吗?
> > 
> > 也不是 还有一个，是我的good friend 不过他没GitHub的号 我早就劝他注册一个了 结果一拖再拖
> 
> 你帮他搞一个我想见见

他注册了  
@H3gg387

**Comment by Minemetero** [comment]
> > 35.677, 139.775
> 
> 啊？
> 
> ![Screenshot_20240520_204841_com.microsoft.emmx.jpg](https://private-user-images.githubusercontent.com/148617407/332069796-1bc5367f-0b27-46c2-b990-8693c80c9a88.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDcwMDksIm5iZiI6MTcxNjI0NjcwOSwicGF0aCI6Ii8xNDg2MTc0MDcvMzMyMDY5Nzk2LTFiYzUzNjdmLTBiMjctNDZjMi1iOTkwLTg2OTNjODBjOWE4OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMzExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjAwYWVmMmM0ZTMyYTk2YmI5ODM1NmZlNWFjY2MyNzhjOGQzOTIyMDJkNTlmNWFkM2E0ODg0MThjODc4ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9Jqx8-UG1BuEeo-8vRUT1VQsV8Rl53UiZEcj84O-80)

位置不能给具体了大概就那样

**Comment by Minemetero** [comment]
> > > > 全班就你一个会敲代码吗?
> > > 
> > > 
> > > 也不是 还有一个，是我的good friend 不过他没GitHub的号 我早就劝他注册一个了 结果一拖再拖
> > 
> > 
> > 你帮他搞一个我想见见
> 
> 他注册了 @H3gg387

他的Profile写错了不是lingbo是lingbopro..我本來还想问你几年级看来没必要了 ：）你同学给的信息太多了

**Comment by lingbopro** [comment]
> > > 35.677, 139.775
> > 
> > 啊？
> > 
> > ![Screenshot_20240520_204841_com.microsoft.emmx.jpg](https://private-user-images.githubusercontent.com/148617407/332069796-1bc5367f-0b27-46c2-b990-8693c80c9a88.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDcwMDksIm5iZiI6MTcxNjI0NjcwOSwicGF0aCI6Ii8xNDg2MTc0MDcvMzMyMDY5Nzk2LTFiYzUzNjdmLTBiMjctNDZjMi1iOTkwLTg2OTNjODBjOWE4OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMzExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjAwYWVmMmM0ZTMyYTk2YmI5ODM1NmZlNWFjY2MyNzhjOGQzOTIyMDJkNTlmNWFkM2E0ODg0MThjODc4ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9Jqx8-UG1BuEeo-8vRUT1VQsV8Rl53UiZEcj84O-80)
> 
> 位置不能给具体了大概就那样

我也没必要知道你地址啊，我又不去你那拆网线（

**Comment by Minemetero** [comment]
> > > > 35.677, 139.775
> > > 
> > > 
> > > 啊？
> > > ![Screenshot_20240520_204841_com.microsoft.emmx.jpg](https://private-user-images.githubusercontent.com/148617407/332069796-1bc5367f-0b27-46c2-b990-8693c80c9a88.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDcwMDksIm5iZiI6MTcxNjI0NjcwOSwicGF0aCI6Ii8xNDg2MTc0MDcvMzMyMDY5Nzk2LTFiYzUzNjdmLTBiMjctNDZjMi1iOTkwLTg2OTNjODBjOWE4OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQyMzExNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjAwYWVmMmM0ZTMyYTk2YmI5ODM1NmZlNWFjY2MyNzhjOGQzOTIyMDJkNTlmNWFkM2E0ODg0MThjODc4ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9Jqx8-UG1BuEeo-8vRUT1VQsV8Rl53UiZEcj84O-80)
> > 
> > 
> > 位置不能给具体了大概就那样
> 
> 我也没必要知道你地址啊，我又不去你那拆网线（

:>

**Comment by lingbopro** [comment]
虽然但是，是不是可以关了（
